cse-config-order: 100

service_description:
  name: customer-website

cse:

  rest:
    address: 0.0.0.0:9091
    server:
      thread-count: 10
## static web site will token root
    servlet:
      urlPattern: /api/*

## Spring Boot configurations
server:
  port: 9091
spring:
  application:
    name: customer-website
